python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5   --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5   --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5   --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5   --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5   --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5   --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5   --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5   --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5   --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5   --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5   --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5   --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5  --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5  --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5  --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5  --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5  --two_hop --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5  --two_hop --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5  --two_hop --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5  --two_hop --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5  --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5  --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5  --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5  --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x  --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x  --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x  --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x  --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x  --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x  --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x  --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x  --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x  --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x  --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x  --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x  --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x --two_hop --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x --two_hop --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x --two_hop --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x --two_hop --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 5 --combine_x --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10   --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10   --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10   --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10   --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10   --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10   --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10   --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10   --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10   --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10   --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10   --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10   --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10  --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10  --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10  --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10  --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10  --two_hop --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10  --two_hop --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10  --two_hop --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10  --two_hop --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10  --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10  --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10  --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10  --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x  --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x  --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x  --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x  --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x  --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x  --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x  --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x  --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x  --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x  --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x  --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x  --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x --two_hop --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x --two_hop --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x --two_hop --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x --two_hop --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 10 --combine_x --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15   --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15   --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15   --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15   --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15   --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15   --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15   --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15   --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15   --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15   --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15   --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15   --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15  --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15  --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15  --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15  --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15  --two_hop --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15  --two_hop --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15  --two_hop --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15  --two_hop --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15  --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15  --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15  --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15  --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x  --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x  --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x  --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x  --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x  --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x  --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x  --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x  --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x  --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x  --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x  --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x  --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x --two_hop --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x --two_hop --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x --two_hop --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x --two_hop --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 5 --high_k 15 --combine_x --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5   --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5   --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5   --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5   --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5   --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5   --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5   --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5   --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5   --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5   --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5   --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5   --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5  --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5  --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5  --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5  --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5  --two_hop --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5  --two_hop --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5  --two_hop --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5  --two_hop --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5  --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5  --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5  --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5  --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x  --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x  --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x  --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x  --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x  --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x  --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x  --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x  --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x  --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x  --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x  --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x  --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x --two_hop --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x --two_hop --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x --two_hop --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x --two_hop --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 5 --combine_x --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10   --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10   --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10   --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10   --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10   --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10   --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10   --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10   --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10   --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10   --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10   --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10   --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10  --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10  --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10  --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10  --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10  --two_hop --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10  --two_hop --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10  --two_hop --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10  --two_hop --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10  --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10  --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10  --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10  --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x  --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x  --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x  --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x  --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x  --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x  --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x  --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x  --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x  --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x  --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x  --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x  --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x --two_hop --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x --two_hop --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x --two_hop --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x --two_hop --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 10 --combine_x --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15   --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15   --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15   --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15   --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15   --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15   --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15   --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15   --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15   --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15   --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15   --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15   --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15  --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15  --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15  --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15  --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15  --two_hop --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15  --two_hop --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15  --two_hop --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15  --two_hop --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15  --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15  --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15  --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15  --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x  --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x  --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x  --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x  --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x  --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x  --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x  --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x  --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x  --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x  --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x  --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x  --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x --two_hop --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x --two_hop --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x --two_hop --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x --two_hop --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 10 --high_k 15 --combine_x --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5   --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5   --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5   --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5   --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5   --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5   --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5   --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5   --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5   --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5   --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5   --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5   --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5  --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5  --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5  --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5  --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5  --two_hop --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5  --two_hop --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5  --two_hop --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5  --two_hop --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5  --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5  --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5  --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5  --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x  --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x  --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x  --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x  --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x  --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x  --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x  --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x  --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x  --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x  --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x  --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x  --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x --two_hop --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x --two_hop --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x --two_hop --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x --two_hop --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 5 --combine_x --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10   --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10   --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10   --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10   --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10   --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10   --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10   --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10   --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10   --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10   --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10   --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10   --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10  --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10  --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10  --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10  --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10  --two_hop --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10  --two_hop --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10  --two_hop --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10  --two_hop --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10  --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10  --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10  --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10  --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x  --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x  --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x  --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x  --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x  --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x  --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x  --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x  --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x  --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x  --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x  --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x  --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x --two_hop --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x --two_hop --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x --two_hop --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x --two_hop --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 10 --combine_x --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15   --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15   --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15   --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15   --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15   --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15   --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15   --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15   --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15   --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15   --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15   --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15   --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15  --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15  --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15  --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15  --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15  --two_hop --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15  --two_hop --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15  --two_hop --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15  --two_hop --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15  --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15  --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15  --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15  --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x  --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x  --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x  --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x  --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x  --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x  --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x  --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x  --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x  --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x  --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x  --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x  --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x --two_hop --edge hard_num --md high  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x --two_hop --edge hard_num --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x --two_hop --edge hard_num --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x --two_hop --edge hard_num --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x --two_hop --edge hard_num --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x --two_hop --edge hard_num --md union  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x --two_hop --edge hard_num --md intersect  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x --two_hop --edge hard_num --md low  --num_layer 2 
python HLCL_hard.py --device 4 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 15 --high_k 15 --combine_x --two_hop --edge hard_num --md high  --num_layer 2 
