python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md union  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md union  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md low  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md low  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md high  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md high  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md union --intraview_negs --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md union --intraview_negs --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md low --intraview_negs --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md low --intraview_negs --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md high --intraview_negs --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md high --intraview_negs --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md union  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md union  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md low  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md low  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md high  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0   --edge soft --md high  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md union  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md union  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md low  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md low  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md high  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md high  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md union --intraview_negs --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md union --intraview_negs --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md low --intraview_negs --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md low --intraview_negs --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md high --intraview_negs --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md high --intraview_negs --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md union  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md union  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md low  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md low  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md high  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0  --two_hop --edge soft --md high  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md union  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md union  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md low  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md low  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md high  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md high  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md union --intraview_negs --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md union --intraview_negs --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md low --intraview_negs --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md low --intraview_negs --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md high --intraview_negs --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md high --intraview_negs --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md union  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md union  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md low  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md low  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md high  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x  --edge soft --md high  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md union  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md union  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md low  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md low  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md high  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md high  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md union --intraview_negs --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md union --intraview_negs --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md low --intraview_negs --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md low --intraview_negs --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md high --intraview_negs --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md high --intraview_negs --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md union  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md union  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md low  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md low  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md high  --num_layer 3 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0 --high_k 0 --combine_x --two_hop --edge soft --md high  --num_layer 4 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.2 --combine_x  --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3   --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3   --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3   --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3   --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3   --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3   --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3   --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3   --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3   --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3   --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3   --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3   --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3  --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3  --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3  --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3  --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3  --two_hop --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3  --two_hop --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3  --two_hop --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3  --two_hop --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3  --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3  --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3  --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3  --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x  --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x  --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x  --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x  --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x  --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x  --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x  --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x  --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x  --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x  --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x  --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x  --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4   --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4   --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4   --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4   --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4   --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4   --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4   --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4   --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4   --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4   --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4   --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4   --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4  --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4  --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4  --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4  --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4  --two_hop --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4  --two_hop --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4  --two_hop --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4  --two_hop --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4  --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4  --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4  --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4  --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x  --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x  --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x  --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x  --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x  --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x  --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x  --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x  --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x  --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x  --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x  --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x  --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.3 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1   --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1   --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1   --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1   --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1   --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1   --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1   --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1   --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1   --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1   --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1   --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1   --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1  --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1  --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1  --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1  --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1  --two_hop --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1  --two_hop --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1  --two_hop --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1  --two_hop --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1  --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1  --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1  --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1  --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x  --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x  --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x  --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x  --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x  --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x  --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x  --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x  --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x  --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x  --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x  --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x  --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x --two_hop --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x --two_hop --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x --two_hop --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x --two_hop --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.1 --combine_x --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2   --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2   --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2   --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2   --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2   --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2   --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2   --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2   --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2   --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2   --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2   --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2   --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2  --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2  --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2  --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2  --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2  --two_hop --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2  --two_hop --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2  --two_hop --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2  --two_hop --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2  --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2  --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2  --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2  --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x  --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x  --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x  --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x  --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x  --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x  --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x  --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x  --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x  --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x  --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x  --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x  --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.2 --combine_x --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3   --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3   --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3   --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3   --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3   --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3   --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3   --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3   --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3   --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3   --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3   --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3   --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3  --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3  --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3  --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3  --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3  --two_hop --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3  --two_hop --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3  --two_hop --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3  --two_hop --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3  --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3  --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3  --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3  --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x  --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x  --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x  --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x  --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x  --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x  --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x  --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x  --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x  --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x  --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x  --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x  --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.3 --combine_x --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4   --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4   --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4   --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4   --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4   --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4   --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4   --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4   --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4   --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4   --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4   --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4   --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4  --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4  --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4  --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4  --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4  --two_hop --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4  --two_hop --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4  --two_hop --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4  --two_hop --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4  --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4  --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4  --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4  --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x  --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x  --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x  --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x  --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x  --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x  --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x  --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x  --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x  --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x  --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x  --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x  --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md high  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md union --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md intersect --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md low --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md high --intraview_negs --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md union  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md intersect  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md low  --num_layer 2 
python HLCL_hard.py --device 7 --dataset squirrel --pre_learning_rate 0.001 --aug1 0.2 --aug2 0.2 --runs 5 --per_epoch 25 --low_k 0.4 --high_k 0.4 --combine_x --two_hop --edge hard_ratio --md high  --num_layer 2 
